#!/bin/bash

# php agent properties
CLI_ARGS=""

# if ssl true then -s
if [ "${APPDYNAMICS_CONTROLLER_SSL_ENABLED}" = "true" ]; then
    CLI_ARGS="-s "
fi

if [ ! -z "${APPDYNAMICS_AGENT_LOG_DIR}" ]; then
    mkdir -p ${APPDYNAMICS_AGENT_LOG_DIR}
    chmod 777 ${APPDYNAMICS_AGENT_LOG_DIR}
    CLI_ARGS="${CLI_ARGS} --log-dir=${APPDYNAMICS_AGENT_LOG_DIR}"
fi

CLI_ARGS="${CLI_ARGS} -a ${APPDYNAMICS_AGENT_ACCOUNT_NAME}@${APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY}"
CLI_ARGS="${CLI_ARGS} ${APPDYNAMICS_CONTROLLER_HOST_NAME}"
CLI_ARGS="${CLI_ARGS} ${APPDYNAMICS_CONTROLLER_PORT}"
CLI_ARGS="${CLI_ARGS} ${APPDYNAMICS_AGENT_APPLICATION_NAME}"
CLI_ARGS="${CLI_ARGS} ${APPDYNAMICS_AGENT_TIER_NAME}"
CLI_ARGS="${CLI_ARGS} ${APPDYNAMICS_AGENT_NODE_NAME}"

echo "CLI_ARGS: $CLI_ARGS"

chmod +x ${PHP_AGENT_DIR}/appdynamics-php-agent-linux_x64/install.sh
${PHP_AGENT_DIR}/appdynamics-php-agent-linux_x64/install.sh $CLI_ARGS
